[project]
name = "day-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.1",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "osmnx>=2.0.6",
    "pandas>=2.3.3",
    "shapely>=2.1.2",
]
